name: Execute build on PR

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Run precheck script
        run: pwd && sh .github/workflows/scripts/precheck.sh
        shell: bash

  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11, 17]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Copy source files
        uses: actions/checkout@v3

      - name: Set up JDKs
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Execute Gradle build
        run: ./gradlew clean build
